-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDlNbDe8J9dWqQBdj
ZnK1BoL+bs0pI7JSeuxkBK/k4FGgCgYIKoZIzj0DAQehRANCAARvALeBPcmo7OyS
rykyyvD2v+rWMmu9pfUl5AvwvkBZNDTGLcR5FrJbKNQ4j+tlcisysP5tKnShzNXj
B1jM4Ry+
-----END PRIVATE KEY-----